spring:
  application:
    name: LibraryManagementSystem

  datasource:
    url: jdbc:sqlite:book.db
    driver-class-name: org.sqlite.JDBC

mybatis:
  configuration:
    map-underscore-to-camel-case: true

